server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:user-service-db
    driver-class-name: org.h2.Driver
    username: root
    password: root

keycloak:
  server-url: http://localhost:8080
  realm-name: e-learning-platform
  admin-cli-client-id: admin-cli
  admin-cli-client-secret: 6dpnnNwXp28QfURc7FY45Zanp3BNatGY